<h1>
 Title: try-catch statement &amp; terminate program
</h1>
<h3>
 Author: Anonymous
</h3>
<h3>
 Date: 2021-10-06T02:33:27.365784+11:00
</h3>
<h3>
 Category: General
</h3>
<h3>
 Vote Count: 0
</h3>
<p>
 Hi! If it throws an new error  in a catch statement, why is it only thrown out of the cell of try-catch statement, but does not terminate the program?
</p>
<h3>
 ----------- REPLIES -----------
</h3>
<div style="text-indent: 2em;">
 <h3>
  Author: Varun Gande (student)
 </h3>
 <h3>
  Vote Count: 0
 </h3>
 <p>
  What if that try-catch statement is enclosed in another try/catch block? Does the program terminate?
 </p>
 <h3>
  ------------------------------------
 </h3>
</div>